version: "3.6"
services:
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: 'rabbitmq'
        ports:
          - "5672:5672"
          - "15672:15672"
        restart: always 
        networks:
          - rabbitmq_backend
networks:
  rabbitmq_backend:
    driver: bridge